# Description: This file is used to define the geometry of the detector.
#             The geometry is defined by a list of parts, each of which
#             is a separate STL file. Each part can have its own material
#             properties, and can be marked as a detector or not.
#
#             Colors can be specified in hexadecimal, e.g. 0x00ff00 for green,
#             as a string, e.g. 'green', or as a uint32, e.g. 0x00ff00ff for
#             green with full opacity. All matplotlib colors are supported
#

target: vacuum
log: true

parts:
  - name: sipm_tiles
    is_detector: true

    # Note: each file in the path will be loaded as a separate part with its own channel!
    path: "/home/sam/sw/chroma-lxe/data/stl/sipm_channels/*.STL"

    # The scale factor to apply to the STL file
    scale: 1.0

    # The rotation to apply to the STL file
    rotation:
      dir: [0.0, 0.0, 0.0]
      angle: 0.0  # in degrees

    # The translation to apply to the STL file
    translation: [-34.103, -62.519, -34.15]

    # material properties
    material:
      surface: perfect_detector
      material1: ceramic
      material2: lxe
      color: orangered

  - name: sipm_ceramic_board
    is_detector: false
    path: "/home/sam/sw/chroma-lxe/data/stl/sipm_ceramic_board.STL"

    # The scale factor to apply to the STL file
    scale: 1.0

    # The rotation to apply to the STL file
    rotation:
      dir: [0.0, 0.0, 0.0]
      angle: 0.0  # in degrees

    # The translation to apply to the STL file
    translation: [-34.103, -62.53, -34.15]

    # material properties
    material:
      surface: ceramic
      material1: ceramic
      material2: lxe
      color: 0xFFFFFF

  - name: simplified_anode_substrate
    is_detector: false
    path: "/home/sam/sw/chroma-lxe/data/stl/simplified_anode_substrate.STL"

    # The scale factor to apply to the STL file
    scale: 1.0

    # The rotation to apply to the STL file
    rotation:
      dir: [0, 1, 0]
      angle: -112  # in degrees

    # The translation to apply to the STL file
    translation: [-23.725, 6.4341, 64.523]

    # material properties
    material:
      surface: ceramic
      material1: ceramic
      material2: lxe
      color: 0xFFFFFF

  - name: simplified_anode
    is_detector: false
    path: "/home/sam/sw/chroma-lxe/data/stl/simplified_anode.STL"

    # The scale factor to apply to the STL file
    scale: 1.0

    # The rotation to apply to the STL file 
    rotation:
      dir: [0, 1, 0]
      angle: -112  # in degrees

    # The translation to apply to the STL file
    translation: [-19.795, 6.2, 55.423] #5.9041

    # material properties
    material:
      surface: gold
      material1: ceramic
      material2: lxe
      color: 0xFFCC00

  - name: tpc_assembly
    is_detector: false
    path: "/home/sam/sw/chroma-lxe/data/stl/short_tpc_assembly_modulo_anode_sipm.STL"

    # The scale factor to apply to the STL file
    scale: 1.0

    # The rotation to apply to the STL file
    rotation:
      dir: [0, 0, 0]
      angle: 0  # in degrees

    # The translation to apply to the STL file
    translation: [0,0,0]

    # material properties
    material:
      surface: steel
      material1: steel
      material2: lxe
      color: 0xC83B3B3B